name: ci

on:
  pull_request

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 17
      uses: actions/setup-node@v4
      with:
        node-version: 17
    - run: npm i
    - run: npm run test:ci
    - run: npm run lint
    - run: npm publish --dry-run
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
